rails_home_link: "https://www.railstutorial.org/"
rails_help_link: "https://www.railstutorial.org/help"
rails_book_link: "https://www.railstutorial.org/book"
rails_web_link: "https://rubyonrails.org/"
rails_contact_link: "https://www.railstutorial.org/contact"
rails_about_link: "https://www.railstutorial.org/about"
rails_tutorial_author: "https://www.michaelhartl.com/"
rails_news_link: "https://news.railstutorial.org/"
rails_image_path: "rails.svg"
posts_per_page: 10
max_content_length: 140
gravatar_email: "http://gravatar.com/emails"
image_size: 50
users_per_page: 5
reset_pass_hours_expired: 2
image_types_accept: "image/jpeg,image/gif,image/png"
max_image_size: 5
image_size_limit:
  - 500
  - 500
validate:
  email:
    min_length: 10
    max_length: 255
    regex: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    case_sensitive: false
  name:
    max_length: 30
  password:
    min_length: 6
