rails_home_link: "https://www.railstutorial.org/"
rails_help_link: "https://www.railstutorial.org/help"
rails_book_link: "https://www.railstutorial.org/book"
rails_web_link: "https://rubyonrails.org/"
rails_contact_link: "https://www.railstutorial.org/contact"
rails_about_link: "https://www.railstutorial.org/about"
rails_tutorial_author: "https://www.michaelhartl.com/"
rails_news_link: "https://news.railstutorial.org/"
rails_image_path: "rails.svg"
